# coding: utf-8

"""
    Timmi Absences API

    Welcome on the documentation for Timmi Absences API.

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredImportsEntitlementsBatchImportRequest(TypedDict):
    pass

class OptionalImportsEntitlementsBatchImportRequest(TypedDict, total=False):
    File: str

    # Description of the entries generated by the import (visible to users in the account details).
    Description: str

    # Reference date (text mode). Respect the format: yyyy-MM-ddThh: mm: ss
    ReferenceDate: datetime

class ImportsEntitlementsBatchImportRequest(RequiredImportsEntitlementsBatchImportRequest, OptionalImportsEntitlementsBatchImportRequest):
    pass
