# coding: utf-8

"""
    Timmi Absences API

    Welcome on the documentation for Timmi Absences API.

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_timmi_absences_python_sdk.paths.api_v3_services_import_leave_periods.post import AbsenceBatchCreate
from lucca_timmi_absences_python_sdk.paths.timmi_absences_api_imports_v1_0_leave_periods.post import CreateAbsencesBatch
from lucca_timmi_absences_python_sdk.paths.figgo_api_public_services_v1_0_leave_entitlements_import.post import EntitlementsBatchImport
from lucca_timmi_absences_python_sdk.paths.timmi_absences_api_imports_v1_0_leave_periods_summary_id_progress.get import GetProgress
from lucca_timmi_absences_python_sdk.paths.timmi_absences_api_public_services_v1_0_leave_entitlements_import.post import ImportLeaveEntitlements
from lucca_timmi_absences_python_sdk.paths.figgo_api_public_services_v1_0_leave_entitlements_replace.post import ReplaceEntitlements
from lucca_timmi_absences_python_sdk.paths.timmi_absences_api_public_services_v1_0_leave_entitlements_replace.post import ReplaceEntitlements0
from lucca_timmi_absences_python_sdk.apis.tags.imports_api_raw import ImportsApiRaw


class ImportsApi(
    AbsenceBatchCreate,
    CreateAbsencesBatch,
    EntitlementsBatchImport,
    GetProgress,
    ImportLeaveEntitlements,
    ReplaceEntitlements,
    ReplaceEntitlements0,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ImportsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ImportsApiRaw(api_client)
