# coding: utf-8

"""
    Timmi Absences API

    Welcome on the documentation for Timmi Absences API.

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_timmi_absences_python_sdk.paths.api_v3_leaves_leave_id.delete import CancelLeaveByIdRaw
from lucca_timmi_absences_python_sdk.paths.api_v3_leaves.get import GetApprovedListRaw
from lucca_timmi_absences_python_sdk.paths.api_v3_leaves_leave_id.get import GetByIdRaw


class LeavesApiRaw(
    CancelLeaveByIdRaw,
    GetApprovedListRaw,
    GetByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
