# coding: utf-8

"""
    Timmi Absences API

    Welcome on the documentation for Timmi Absences API.

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_timmi_absences_python_sdk.paths.api_v3_leaves_leave_id.delete import CancelLeaveById
from lucca_timmi_absences_python_sdk.paths.api_v3_leaves.get import GetApprovedList
from lucca_timmi_absences_python_sdk.paths.api_v3_leaves_leave_id.get import GetById
from lucca_timmi_absences_python_sdk.apis.tags.leaves_api_raw import LeavesApiRaw


class LeavesApi(
    CancelLeaveById,
    GetApprovedList,
    GetById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: LeavesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = LeavesApiRaw(api_client)
