# coding: utf-8

"""
    Timmi Absences API

    Welcome on the documentation for Timmi Absences API.

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lucca_timmi_absences_python_sdk import schemas  # noqa: F401


class ImportsEntitlementsBatchImportResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            successLinesCount = schemas.IntSchema
            globalErrors = schemas.DictSchema
            lineErrors = schemas.DictSchema
            __annotations__ = {
                "successLinesCount": successLinesCount,
                "globalErrors": globalErrors,
                "lineErrors": lineErrors,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["successLinesCount"]) -> MetaOapg.properties.successLinesCount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["globalErrors"]) -> MetaOapg.properties.globalErrors: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lineErrors"]) -> MetaOapg.properties.lineErrors: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["successLinesCount", "globalErrors", "lineErrors", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["successLinesCount"]) -> typing.Union[MetaOapg.properties.successLinesCount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["globalErrors"]) -> typing.Union[MetaOapg.properties.globalErrors, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lineErrors"]) -> typing.Union[MetaOapg.properties.lineErrors, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["successLinesCount", "globalErrors", "lineErrors", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        successLinesCount: typing.Union[MetaOapg.properties.successLinesCount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        globalErrors: typing.Union[MetaOapg.properties.globalErrors, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        lineErrors: typing.Union[MetaOapg.properties.lineErrors, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ImportsEntitlementsBatchImportResponse':
        return super().__new__(
            cls,
            *args,
            successLinesCount=successLinesCount,
            globalErrors=globalErrors,
            lineErrors=lineErrors,
            _configuration=_configuration,
            **kwargs,
        )
